---
name: App-Editor-GVip
version: 0.01_01.1
author:
  - 'Nadim ibn hamouda el Khemir. <nkh@cpan.org>'
abstract: gnome interface to Text::Editor::Vip
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Readonly: 0
  Sub::Exporter: 0
  Text::Editor::Vip: 0
build_requires:
  Test::Block: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Warn: 0
  Text::Diff: 0
provides:
  App::Editor::GVip:
    file: lib/App/Editor/GVip.pm
    version: 0.01_01
  App::Editor::GVip::Menu:
    file: lib/App/Editor/GVip/Menu.pm
  App::Editor::GVip::View:
    file: lib/App/Editor/GVip/View.pm
  Lexer::Perl:
    file: setup/Language/Perl/Perl.pm
  SmedView:
    file: setup/Language/Perl/SmedView.spl
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
